version: 0.2
phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run cdk:deploy:quick
      - npm run extension:ci
      - npm run extension:build
artifacts:
  files:
    - '**/*'
  base-directory: 'generative-ai-use-cases-jp/browser-extension/dist'
  discard-paths: no
